version: '3.4'
services:
  store:
    build:
      context: .
      dockerfile: docker/store/Dockerfile
    volumes:
        - ./backend/:/home/backend

  http:
    image: nginx:alpine
    working_dir: /home/backend
    volumes:
      - ./backend/:/home/backend/ 
      - ./docker/http/backend.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./docker/data/db:/var/lib/mysql

